#if !defined(AFX_ISWITCHPANELX_H__EB655BED_F397_4201_9BB9_8A2DDE72C19B__INCLUDED_)
#define AFX_ISWITCHPANELX_H__EB655BED_F397_4201_9BB9_8A2DDE72C19B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CiSwitchPanelX wrapper class

class CiSwitchPanelX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CiSwitchPanelX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8fb1df7e, 0x747f, 0x44ca, { 0xa5, 0xae, 0x6b, 0x0, 0x82, 0xf2, 0x99, 0xb2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString GetPositionCaption1();
	void SetPositionCaption1(LPCTSTR lpszNewValue);
	CString GetPositionCaption2();
	void SetPositionCaption2(LPCTSTR lpszNewValue);
	CString GetPositionCaption3();
	void SetPositionCaption3(LPCTSTR lpszNewValue);
	COleFont GetPanelFontInactive();
	void SetPanelFontInactive(LPDISPATCH newValue);
	COleFont GetPanelFontActive();
	void SetPanelFontActive(LPDISPATCH newValue);
	unsigned long GetPanelBackGroundColor();
	void SetPanelBackGroundColor(unsigned long newValue);
	double GetPanelMarginTop();
	void SetPanelMarginTop(double newValue);
	double GetPanelMarginRow();
	void SetPanelMarginRow(double newValue);
	double GetPanelMarginBottom();
	void SetPanelMarginBottom(double newValue);
	long GetPositionCount();
	void SetPositionCount(long nNewValue);
	long GetPosition();
	void SetPosition(long nNewValue);
	unsigned long GetKnobOuterColor();
	void SetKnobOuterColor(unsigned long newValue);
	unsigned long GetKnobInnerColor();
	void SetKnobInnerColor(unsigned long newValue);
	unsigned long GetKnobHandleColor();
	void SetKnobHandleColor(unsigned long newValue);
	long GetKnobHandleWidth();
	void SetKnobHandleWidth(long nNewValue);
	long GetKnobRadius();
	void SetKnobRadius(long nNewValue);
	long GetKnobSideMargin();
	void SetKnobSideMargin(long nNewValue);
	BOOL GetKnobRadiusAutoSize();
	void SetKnobRadiusAutoSize(BOOL bNewValue);
	long GetMouseControlStyle();
	void SetMouseControlStyle(long nNewValue);
	long GetBorderStyle();
	void SetBorderStyle(long nNewValue);
	unsigned long GetBackGroundColorTop();
	void SetBackGroundColorTop(unsigned long newValue);
	unsigned long GetBackGroundColor();
	void SetBackGroundColor(unsigned long newValue);
	long GetUpdateFrameRate();
	void SetUpdateFrameRate(long nNewValue);
	void Lock();
	void Unlock();
	void RepaintAll();
	void SaveImageToMetaFile(LPCTSTR FileName);
	long OPCAddItem();
	long OPCItemCount();
	void OPCRemoveAllItems();
	void OPCItemActivate(long Index);
	void OPCItemDeactivate(long Index);
	void OPCItemLoaded(long Index);
	CString GetOPCItemComputerName(long Index);
	CString GetOPCItemServerName(long Index);
	CString GetOPCItemItemName(long Index);
	CString GetOPCItemPropertyName(long Index);
	BOOL GetOPCItemAutoConnect(long Index);
	long GetOPCItemUpdateRate(long Index);
	void SetOPCItemComputerName(long Index, LPCTSTR Value);
	void SetOPCItemServerName(long Index, LPCTSTR Value);
	void SetOPCItemItemName(long Index, LPCTSTR Value);
	void SetOPCItemPropertyName(long Index, LPCTSTR Value);
	void SetOPCItemAutoConnect(long Index, BOOL Value);
	void SetOPCItemUpdateRate(long Index, long Value);
	void BeginUpdate();
	void EndUpdate();
	void SaveImageToBitmap(LPCTSTR FileName);
	void SaveImageToJPEG(LPCTSTR FileName, long Compression, BOOL Progressive);
	VARIANT GetBytesJPEG(long Compression, BOOL Progressive);
	void SavePropertiesToFile(LPCTSTR FileName);
	void LoadPropertiesFromFile(LPCTSTR FileName);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	BOOL GetOptionSaveAllProperties();
	void SetOptionSaveAllProperties(BOOL bNewValue);
	void AboutBox();
	unsigned long GetPanelFontInactiveColor();
	void SetPanelFontInactiveColor(unsigned long newValue);
	unsigned long GetPanelFontActiveColor();
	void SetPanelFontActiveColor(unsigned long newValue);
	long GetObjectPointer();
	long GetComponentHandle();
	void ShowPropertyEditor();
	BOOL GetAutoFrameRate();
	void SetAutoFrameRate(BOOL bNewValue);
	void iPaintToDC(long X, long Y, BOOL Transparent, long DC);
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	void OPCItemUpdateResume(long Index);
	void OPCItemUpdateSuspend(long Index);
	VARIANT GetOPCItemData(long Index);
	short GetOPCItemQuality(long Index);
	double GetOPCItemTimeStamp(long Index);
	void SetOPCItemData(long Index, const VARIANT& Value);
	BOOL GetOPCItemActive(long Index);
	CString GetOPCItemGroupName(long Index);
	void SetOPCItemGroupName(long Index, LPCTSTR Value);
	void OPCDeleteItem(long Index);
	void OPCItemActivateSuspend(long Index);
	VARIANT GetBytesPNG(long Compression);
	void SaveImageToPNG(LPCTSTR FileName, long Compression);
	VARIANT GetOPCItemDataNow(long Index, short* Quality);
	BOOL GetOPCItemUpdateSuspended(long Index);
	double GetOPCItemScalar(long Index);
	double GetOPCItemOffset(long Index);
	void SetOPCItemScalar(long Index, double Value);
	void SetOPCItemOffset(long Index, double Value);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ISWITCHPANELX_H__EB655BED_F397_4201_9BB9_8A2DDE72C19B__INCLUDED_)
